(define (problem strips-gripper6)
   (:domain gripper-strips)
   (:objects rooma roomb ball1 ball2 ball3 ball4 ball5 ball6 left
             right)
   (:init (room rooma)
          (room roomb)
          (ball ball1)
          (ball ball2)
          (ball ball3)
          (ball ball4)
          (ball ball5)
          (ball ball6)
          (gripper left)
          (gripper right)
          (at-robby rooma)
          (free left)
          (free right)
          (at-ball ball1 rooma)
          (at-ball ball2 rooma)
          (at-ball ball3 rooma)
          (at-ball ball4 rooma)
          (at-ball ball5 rooma)
          (at-ball ball6 rooma))
   (:goal (and (at-ball ball1 roomb)
               (at-ball ball2 roomb)
               (at-ball ball3 roomb)
               (at-ball ball4 roomb)
               (at-ball ball5 roomb))))
